# Generated by Django 5.1.3 on 2025-03-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The404s', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to='passport/'),
        ),
        migrations.AddField(
            model_name='studentschooldetails',
            name='entry_mode',
            field=models.CharField(blank=True, choices=[('UTME', 'UTME'), ('Direct Entry', 'Direct Entry')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentschooldetails',
            name='entry_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='studentschooldetails',
            name='mode_of_study',
            field=models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentschooldetails',
            name='programme_type',
            field=models.CharField(blank=True, choices=[('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentschooldetails',
            name='semester',
            field=models.CharField(blank=True, choices=[('First Semester', 'First Semester'), ('Second Semester', 'Second Semester')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentschooldetails',
            name='session',
            field=models.CharField(blank=True, choices=[('2020/2021', '2020/2021'), ('2021/2022', '2021/2022')], max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='courseenrollment',
            name='course',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='guardian_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='n_o_k_contact',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='course',
            field=models.ManyToManyField(blank=True, null=True, related_name='courses', to='The404s.usercourses'),
        ),
    ]
